[package]
name = "faketty"
version = "1.0.7"
authors = ["David Tolnay <dtolnay@gmail.com>"]
description = "Wrapper to exec a command in a pty, even if redirecting the output"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/dtolnay/faketty"

[dependencies]
clap = { version = "3.2.5", features = ["deprecated"] }
nix = { version = "0.24", default-features = false, features = ["fs", "process", "term"] }

[dev-dependencies]
scratch = "1.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
